const { chromium } = require('C:/Users/falah/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1282,height:930}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.starts=[];const start=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args){if(this.loop){const data=this.buffer.getChannelData(0);window.starts.push({loop:this.loop,duration:this.buffer.duration,seam:Math.abs(data[0]-data[data.length-1])});}return start.apply(this,args)}});
await page.goto('http://127.0.0.1:3210/?preview=7');await page.getByRole('button',{name:'START',exact:true}).click();await page.waitForTimeout(5000);console.log('Before finish',await page.locator('.music-widget').count(),await page.evaluate(()=>window.starts.length));
await page.waitForSelector('.music-widget.is-playing');console.log('Audio',await page.evaluate(()=>window.starts));
await page.getByRole('button',{name:'Hide music player',exact:true}).click();console.log('Hidden playing',await page.locator('.music-widget.is-playing').count());await page.getByRole('button',{name:'Show music player',exact:true}).click();
await page.getByRole('button',{name:'Pause background music',exact:true}).click();console.log('Paused',await page.locator('.music-widget.is-playing').count());await page.getByRole('button',{name:'Play background music',exact:true}).click();await page.waitForSelector('.music-widget.is-playing');
await page.locator('#music-seek').evaluate(el=>{const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(el,Number(el.max)-.2);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});await page.waitForTimeout(800);console.log('Loop position',await page.locator('#music-seek').inputValue());
await page.getByRole('button',{name:'Mute background music',exact:true}).click();await page.getByRole('button',{name:'Unmute background music',exact:true}).click();
await page.locator('#projects').scrollIntoViewIfNeeded();await page.waitForTimeout(500);console.log('Atmospheres',await page.locator('.section-atmosphere').count(),await page.locator('.section-atmosphere.is-visible').count());await page.screenshot({path:'D:/falah/Documents/Projackssss/portofolio/work/music-desktop.png'});
await page.setViewportSize({width:390,height:844});await page.locator('#contact').scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.screenshot({path:'D:/falah/Documents/Projackssss/portofolio/work/music-mobile.png'});console.log('Overflow',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));console.log('Errors',errors);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
